### ISSUE TITLE
Final file in variable

### ISSUE THREAD

**Issue by frankv12** [khanzadimahdi/UploadManager#2]
Hi, is it possible to get a successful uploaded iamge in a variable? I want to do some extra stuff with the uploaded image(s) after successful upload.

TIA

**Comment by khanzadimahdi** [comment]
you can use callbacks. in this case `afterUpload` can be used

**Comment by frankv12** [comment]
Thanks. I should have been more clear. I was using the call back but don't see how to get the uploaded image.

I've got this function that needs to be called after successful upload for each image:

```
function compressImage($source, $quality)
{
    $info = getimagesize($source);
    if ($info['mime'] == 'image/jpeg') {
        $image = imagecreatefromjpeg($source);
    } elseif ($info['mime'] == 'image/gif') {
        $image = imagecreatefromgif($source);
    } elseif ($info['mime'] == 'image/png') {
        $image = imagecreatefrompng($source);
    }
    imagejpeg($image, NULL, $quality);
}
```
In the callback I'm calling the function. But I have to get the image as a variable. How to get the image instead of the chunks.

`$uploadManager->afterUpload( compressImage($image, 60) );`

Hope you see what I mean.

TIA

**Comment by khanzadimahdi** [comment]
you can compress image after uploading file by using the file's address.
in callback function accessing to the whole image data is not a good idea , because of chunking.
in callbacks you can access to chunks! after upload completes, you can access to the whole file data using its address and you can manipulate it.
