### ISSUE TITLE
Large files can be uploaded in smaller chunks.

### ISSUE THREAD

**Issue by dovancao** [khanzadimahdi/UploadManager#3]
I didn't understand this title. 
In my poor knowledge, client side must slice file into a lot of chunk by using "slice" methods,   then post piece by piece. Is it true?

**Comment by khanzadimahdi** [comment]
yes that's true.
we can slice a large file into many small chunks and then upload them.

1 G = 1024 * 1M   ==> we can slice 1G file into 1024 slices of 1M. and then upload them.

server will retrieve these chunks and stick them together , then the main 1G file will be created.
