### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by falahatiali** [khanzadimahdi/UploadManager#4]
سلام ممنون از پکیج خوبت
سناریوی من اینه که قراره با استفاده از 
postman
فایل رو ارسال کنم که فیلمه. 
باید به صورت چانک چانک ارسال بشه و من دربافت کنم سمت سرور و فایل رو بسازم

**Comment by falahatiali** [comment]
مشکل من اینه کهخ چندین نفر همزمان فایل ارسال میکنند برای آپلود
چجوری بفهمیم کدوم چانک برای کدوم بوده ؟ چون من میخام ای پی آی بنویسم

**Comment by khanzadimahdi** [comment]
یک پروسس برای همه ران نمیشه!

شما در php به ازای هر نفر یک پروسس دارید پس تداخلی در چانک ها نخواهید داشت
همچنین شما میتونید به ازای هر فایل یک ایدی برگردونید که مشخص بشه کدوم چانک برای چه کسی هست

**Comment by falahatiali** [comment]
الان من نمیفهم چجوری استفاده کنم از این پکیج. میخام فایل حجیم آپلود کنم با استفده از پست من
سناریوش چه شکلی میشه

**Comment by falahatiali** [comment]
مثال هاتون ر ونمیفهمم
چجوری فرانت فایل رو میشکنه و چندین چانک تولید میکنه ؟

**Comment by khanzadimahdi** [comment]
نمونه کد مثال گذاشتم.

**Comment by khanzadimahdi** [comment]
پوشه examples در رپازیتوری رو بررسی کنید
