### ISSUE TITLE
how to use this library with codeigniter?

### ISSUE THREAD

**Issue by kanji-stack-dev** [khanzadimahdi/UploadManager#5]
i am codeigniter developer and i am try to upload image with other form field. but i have a one probleam. my upload image size is 1GB so how i can use you library with codeigniter??

**Comment by khanzadimahdi** [comment]
install it using composer , then use the package according to docs.

you can see some examples [here (click)](https://github.com/khanzadimahdi/UploadManager/tree/master/examples) .
