### ISSUE TITLE
این پکیج پشتیبانی میشود؟

### ISSUE THREAD

**Issue by pishguy** [khanzadimahdi/UploadManager#7]
<div dir="rtl">
آخرین به روزرسانی این پکیج مربوط به چند سال پیش هستش. آیا هنوز پشتیبانی میشه؟ مخصوصا روی لاراول هشت؟
</div>

**Comment by khanzadimahdi** [comment]
سلام. بهتره از این پکیج استفاده نکنید چون رلیز جدید بابتش ایجاد نکردم
